//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from lexicalAnalyzer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="lexicalAnalyzerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IlexicalAnalyzerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit([NotNull] lexicalAnalyzerParser.InitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] lexicalAnalyzerParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] lexicalAnalyzerParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncStmt</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.funcInstructions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncStmt([NotNull] lexicalAnalyzerParser.FuncStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.funcParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncParams([NotNull] lexicalAnalyzerParser.FuncParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] lexicalAnalyzerParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.pars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPars([NotNull] lexicalAnalyzerParser.ParsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StmtSlices</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.stmtSlice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtSlices([NotNull] lexicalAnalyzerParser.StmtSlicesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StmtVar</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.stmtVariables"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtVar([NotNull] lexicalAnalyzerParser.StmtVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StmtVarAssign</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.stmtAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtVarAssign([NotNull] lexicalAnalyzerParser.StmtVarAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrintVar</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintVar([NotNull] lexicalAnalyzerParser.PrintVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.instructionIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] lexicalAnalyzerParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.forInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStmt([NotNull] lexicalAnalyzerParser.ForStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.forDeclare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForDeclare([NotNull] lexicalAnalyzerParser.ForDeclareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.switchInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStmt([NotNull] lexicalAnalyzerParser.SwitchStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCases([NotNull] lexicalAnalyzerParser.CasesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>breakTransfer</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.breakInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakTransfer([NotNull] lexicalAnalyzerParser.BreakTransferContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continueTransfer</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.continueInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueTransfer([NotNull] lexicalAnalyzerParser.ContinueTransferContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.returnFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] lexicalAnalyzerParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StmtExpr</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtExpr([NotNull] lexicalAnalyzerParser.StmtExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="lexicalAnalyzerParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] lexicalAnalyzerParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RelationalOperator</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] lexicalAnalyzerParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull([NotNull] lexicalAnalyzerParser.NullContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Character</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter([NotNull] lexicalAnalyzerParser.CharacterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeOf</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOf([NotNull] lexicalAnalyzerParser.TypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDiv([NotNull] lexicalAnalyzerParser.MulDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub([NotNull] lexicalAnalyzerParser.AddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] lexicalAnalyzerParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConvertInt</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvertInt([NotNull] lexicalAnalyzerParser.ConvertIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicOperator</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicOperator([NotNull] lexicalAnalyzerParser.LogicOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] lexicalAnalyzerParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] lexicalAnalyzerParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] lexicalAnalyzerParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Decimal</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimal([NotNull] lexicalAnalyzerParser.DecimalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegateOperator</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegateOperator([NotNull] lexicalAnalyzerParser.NegateOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConvertFloat</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvertFloat([NotNull] lexicalAnalyzerParser.ConvertFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssingVar</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssingVar([NotNull] lexicalAnalyzerParser.AssingVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegate([NotNull] lexicalAnalyzerParser.NegateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionCall</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] lexicalAnalyzerParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] lexicalAnalyzerParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Module</c>
	/// labeled alternative in <see cref="lexicalAnalyzerParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] lexicalAnalyzerParser.ModuleContext context);
}
